zookeeper:
  image: jplock/zookeeper
  ports:
    - "2181:2181"
kafka:
  image: ches/kafka
  links:
    - "zookeeper:zookeeper"
  ports:
    - "9092:9092"
    - "7203:7203"
  volumes:
    - "./data:/data"
    - "./logs:/logs"
postgres:
  image: postgres
  ports:
    - "5432:5432"
  env_file:
    - postgres.env
ircd:
  build: ../docker-ircd
  ports:
    - "6667:6667"
ircdc:
  build: ../ircdc
  ports:
    - "9071:9071"
  volumes:
    - "../ircdc:/ircdc/server"
ircdc_react:
  build: ../ircdc-react
  ports:
    - "9072:9072"
  volumes:
    - "../ircdc-react:/ircdc/react"

