rabbitmq:
  image: rabbitmq:3-management
  hostname: rabbitmq
  restart: always
  ports:
    - "5672:5672"
    - "15672:15672"
  environment:
    - "RABBITMQ_DEFAULT_USER=admin"
    - "RABBITMQ_DEFAULT_PASS=admin"
postgres:
  image: postgres
  ports:
    - "5432:5432"
  env_file:
    - postgres.env
ircd:
  build: ../docker-ircd
  ports:
    - "6667:6667"
ircdc:
  build: ../ircdc
  ports:
    - "9071:9071"
  volumes:
    - "../ircdc:/ircdc/server"
ircdc_react:
  build: ../ircdc-react
  ports:
    - "9072:9072"
  volumes:
    - "../ircdc-react:/ircdc/react"

